import { ProcessInterfaceDescription, Inport, Outport, ProcessInterfaceDescriptionRepository, ProcessPortTemplate } from '@cpt/capacity-planning-simulation-types';

// this is autogenerated by capacity-planning-simulation/lib/cpt-generate-pe-repository.js
export const ProcessingElementRepository: ProcessInterfaceDescriptionRepository =
{
    "acbb16d9-1c4c-4930-a3b4-28a7c33b54e4": {
        "objectId": "acbb16d9-1c4c-4930-a3b4-28a7c33b54e4",
        "objectType": "PROCESS_INTERFACE_DESCRIPTION",
        "implementation": "PROCESSING_ELEMENT",
        "name": "Add Latency",
        "inports": {
            "38563813-210b-4458-8172-4138186966a8": {
                "objectId": "38563813-210b-4458-8172-4138186966a8",
                "objectType": "INPORT",
                "name": "In",
                "requiredTypes": [
                    "NUMBER"
                ],
                "desiredUnits": [
                    "tps"
                ],
                "generatesResponse": "ALWAYS",
                "index": 0
            },
            "edc9a0e8-2ed1-4a8d-9944-b4b11a95ddd4": {
                "objectId": "edc9a0e8-2ed1-4a8d-9944-b4b11a95ddd4",
                "objectType": "INPORT",
                "name": "Mean",
                "requiredTypes": [
                    "NUMBER"
                ],
                "desiredUnits": [],
                "generatesResponse": "NEVER",
                "index": 1
            },
            "fd8cf9bd-0390-4152-9db2-f3c63bee2124": {
                "objectId": "fd8cf9bd-0390-4152-9db2-f3c63bee2124",
                "objectType": "INPORT",
                "name": "StdDev",
                "requiredTypes": [
                    "NUMBER"
                ],
                "desiredUnits": [],
                "generatesResponse": "NEVER",
                "index": 2
            }
        },
        "outports": {
            "8421bb7b-908b-44e6-879e-b3b32c8815d3": {
                "objectId": "8421bb7b-908b-44e6-879e-b3b32c8815d3",
                "objectType": "OUTPORT",
                "name": "Out",
                "types": [
                    "NUMBER"
                ],
                "unit": "tps",
                "index": 0
            }
        },
        "portTemplates": {}
    },
    "51c9c02a-21ce-45f6-be6c-512f01aa0d32": {
        "objectId": "51c9c02a-21ce-45f6-be6c-512f01aa0d32",
        "objectType": "PROCESS_INTERFACE_DESCRIPTION",
        "implementation": "PROCESSING_ELEMENT",
        "name": "Parallel Execution",
        "description": "Forward load downstream. Select max latency response.",
        "inports": {
            "2c09be68-f259-4be5-85e9-9fbbcd048108": {
                "objectId": "2c09be68-f259-4be5-85e9-9fbbcd048108",
                "objectType": "INPORT",
                "name": "In",
                "requiredTypes": [
                    "NUMBER"
                ],
                "desiredUnits": [
                    "tps"
                ],
                "generatesResponse": "ALWAYS",
                "index": 0
            }
        },
        "outports": {
            "2ff959c2-422b-4be3-902b-ca659d690fc1": {
                "objectId": "2ff959c2-422b-4be3-902b-ca659d690fc1",
                "objectType": "OUTPORT",
                "name": "Out-A",
                "types": [
                    "NUMBER"
                ],
                "unit": "tps",
                "index": 1
            },
            "94b5851d-9364-4c90-8497-700a20fb5178": {
                "objectId": "94b5851d-9364-4c90-8497-700a20fb5178",
                "objectType": "OUTPORT",
                "name": "Out-B",
                "types": [
                    "NUMBER"
                ],
                "unit": "tps",
                "index": 2
            }
        },
        "portTemplates": {
            "1a09acf7-3dd5-4ebf-9f01-1872d505512c": {
                "name": "Parallel Output",
                "objectId": "1a09acf7-3dd5-4ebf-9f01-1872d505512c",
                "objectType": "PROCESS_PORT_TEMPLATE",
                "inportTemplates": {},
                "outportTemplates": {
                    "df9e60c2-169c-4d30-a4f7-58564432a261": {
                        "objectId": "df9e60c2-169c-4d30-a4f7-58564432a261",
                        "objectType": "OUTPORT",
                        "name": "Parallel-Out",
                        "types": [
                            "NUMBER"
                        ],
                        "unit": "tps",
                        "index": 0
                    }
                }
            }
        }
    },
    "bd96eec1-483b-44fe-a07b-11bb9141f02f": {
        "objectId": "bd96eec1-483b-44fe-a07b-11bb9141f02f",
        "objectType": "PROCESS_INTERFACE_DESCRIPTION",
        "implementation": "PROCESSING_ELEMENT",
        "name": "Sum",
        "inports": {
            "f37c3cf8-881d-46ba-8715-de76904365c5": {
                "name": "In-A",
                "objectId": "f37c3cf8-881d-46ba-8715-de76904365c5",
                "objectType": "INPORT",
                "requiredTypes": [
                    "NUMBER"
                ],
                "desiredUnits": [],
                "generatesResponse": "PASSTHROUGH",
                "index": 0
            },
            "e4b97aaa-bd31-421a-9948-c30ac1a396c1": {
                "name": "In-B",
                "objectId": "e4b97aaa-bd31-421a-9948-c30ac1a396c1",
                "objectType": "INPORT",
                "requiredTypes": [
                    "NUMBER"
                ],
                "desiredUnits": [],
                "generatesResponse": "PASSTHROUGH",
                "index": 1
            }
        },
        "outports": {
            "8f4c41e4-f501-4374-a34c-62744996349a": {
                "name": "Out",
                "objectId": "8f4c41e4-f501-4374-a34c-62744996349a",
                "objectType": "OUTPORT",
                "types": [
                    "NUMBER"
                ],
                "index": 0
            }
        },
        "portTemplates": {
            "8be3030f-50b1-4a5a-9a51-417d205974bb": {
                "name": "Summand",
                "objectId": "8be3030f-50b1-4a5a-9a51-417d205974bb",
                "objectType": "PROCESS_PORT_TEMPLATE",
                "description": "Add an additional summand inport.",
                "inportTemplates": {
                    "ca210892-da31-4066-8657-55786ffb3642": {
                        "name": "Summand",
                        "objectId": "ca210892-da31-4066-8657-55786ffb3642",
                        "objectType": "INPORT",
                        "requiredTypes": [
                            "NUMBER"
                        ],
                        "desiredUnits": [],
                        "generatesResponse": "PASSTHROUGH",
                        "index": 0
                    }
                },
                "outportTemplates": {}
            }
        }
    },
    "5a615ab0-8960-42e7-a99c-78e5c548bfda": {
        "objectId": "5a615ab0-8960-42e7-a99c-78e5c548bfda",
        "objectType": "PROCESS_INTERFACE_DESCRIPTION",
        "implementation": "PROCESSING_ELEMENT",
        "name": "Add Aspect",
        "description": "Add an aspect (breakdown or tag) to a load. Input has to be a number for this to work.",
        "inports": {
            "d5490871-414c-4b80-8502-5e39721e8feb": {
                "name": "Load",
                "objectId": "d5490871-414c-4b80-8502-5e39721e8feb",
                "objectType": "INPORT",
                "requiredTypes": [
                    "NUMBER"
                ],
                "desiredUnits": [],
                "generatesResponse": "PASSTHROUGH",
                "index": 0,
                "description": "Input of numerical load"
            },
            "301d502f-d421-44c5-a917-864c19b0f008": {
                "name": "Aspect",
                "objectId": "301d502f-d421-44c5-a917-864c19b0f008",
                "objectType": "INPORT",
                "requiredTypes": [
                    "BREAKDOWN",
                    "TAG"
                ],
                "desiredUnits": [],
                "generatesResponse": "NEVER",
                "index": 1,
                "description": "Input of Aspect. Can be defined as port parameter."
            }
        },
        "outports": {
            "b93ad313-aea6-4acb-8162-d5338274a92b": {
                "name": "Out",
                "objectId": "b93ad313-aea6-4acb-8162-d5338274a92b",
                "objectType": "OUTPORT",
                "types": [
                    "NUMBER"
                ],
                "index": 0,
                "description": "Output of Load including Aspect"
            }
        },
        "portTemplates": {}
    },
    "c6a9bfed-4949-4692-b5c3-3906f48bc9ad": {
        "objectId": "c6a9bfed-4949-4692-b5c3-3906f48bc9ad",
        "objectType": "PROCESS_INTERFACE_DESCRIPTION",
        "implementation": "PROCESSING_ELEMENT",
        "name": "Split By Aspect",
        "inports": {
            "07638ad0-7e36-4392-82e0-e90b5898dede": {
                "objectId": "07638ad0-7e36-4392-82e0-e90b5898dede",
                "objectType": "INPORT",
                "name": "Load",
                "requiredTypes": [
                    "NUMBER"
                ],
                "desiredUnits": [],
                "generatesResponse": "PASSTHROUGH",
                "index": 0
            },
            "836a53ce-2a9f-4592-a93c-e9d85e94bc57": {
                "objectId": "836a53ce-2a9f-4592-a93c-e9d85e94bc57",
                "objectType": "INPORT",
                "name": "Aspect Name",
                "requiredTypes": [
                    "STRING"
                ],
                "desiredUnits": [],
                "generatesResponse": "NEVER",
                "index": 1
            }
        },
        "outports": {
            "34703d60-4c73-446a-b7c6-40e4ce92b1b3": {
                "objectId": "34703d60-4c73-446a-b7c6-40e4ce92b1b3",
                "objectType": "OUTPORT",
                "name": "Undefined",
                "types": [
                    "NUMBER"
                ],
                "index": 0
            }
        },
        "portTemplates": {
            "965261aa-e0a6-46a0-aa82-33defa2d4efc": {
                "name": "Slice Output",
                "objectId": "965261aa-e0a6-46a0-aa82-33defa2d4efc",
                "objectType": "PROCESS_PORT_TEMPLATE",
                "description": "Add an output for the slice of the load as defined by the selected aspect.",
                "inportTemplates": {},
                "outportTemplates": {
                    "8cdf6ffc-d33c-4aee-b6cc-571a8f44f0e3": {
                        "name": "Slice Out",
                        "objectId": "8cdf6ffc-d33c-4aee-b6cc-571a8f44f0e3",
                        "objectType": "OUTPORT",
                        "types": [
                            "NUMBER"
                        ],
                        "configType": "STRING",
                        "index": 0
                    }
                }
            }
        }
    },
    "59b677a7-ac5d-40cf-acd5-16a97db17719": {
        "objectId": "59b677a7-ac5d-40cf-acd5-16a97db17719",
        "objectType": "PROCESS_INTERFACE_DESCRIPTION",
        "implementation": "PROCESSING_ELEMENT",
        "name": "Multiply",
        "inports": {
            "92665c3d-9dde-471d-9413-8e59ca17f383": {
                "name": "In-A",
                "objectId": "92665c3d-9dde-471d-9413-8e59ca17f383",
                "objectType": "INPORT",
                "requiredTypes": [
                    "NUMBER"
                ],
                "desiredUnits": [],
                "generatesResponse": "PASSTHROUGH",
                "index": 0
            },
            "2863c566-fe47-47bb-99ef-76a5939c7e96": {
                "name": "In-B",
                "objectId": "2863c566-fe47-47bb-99ef-76a5939c7e96",
                "objectType": "INPORT",
                "requiredTypes": [
                    "NUMBER"
                ],
                "desiredUnits": [],
                "generatesResponse": "PASSTHROUGH",
                "index": 1
            }
        },
        "outports": {
            "b1a554bd-1572-4e8e-ba8f-1a1fa519be72": {
                "name": "Out",
                "objectId": "b1a554bd-1572-4e8e-ba8f-1a1fa519be72",
                "objectType": "OUTPORT",
                "types": [
                    "NUMBER"
                ],
                "index": 0
            },
            "cac91c55-68d9-4859-bb5b-151717572bec": {
                "name": "Out (Custom Unit)",
                "objectId": "cac91c55-68d9-4859-bb5b-151717572bec",
                "objectType": "OUTPORT",
                "types": [
                    "NUMBER"
                ],
                "index": 1,
                "configType": "STRING"
            }
        },
        "portTemplates": {
            "772e3300-5e8f-4cce-a5d9-95116d591d48": {
                "name": "Multiplicand",
                "objectId": "772e3300-5e8f-4cce-a5d9-95116d591d48",
                "objectType": "PROCESS_PORT_TEMPLATE",
                "description": "Add an additional multiplicand inport.",
                "inportTemplates": {
                    "72e1614c-8075-42a6-a407-37b08b5e691d": {
                        "name": "Multiplicand",
                        "objectId": "72e1614c-8075-42a6-a407-37b08b5e691d",
                        "objectType": "INPORT",
                        "requiredTypes": [
                            "NUMBER"
                        ],
                        "desiredUnits": [],
                        "generatesResponse": "PASSTHROUGH",
                        "index": 0
                    }
                },
                "outportTemplates": {}
            }
        }
    },
    "43ec72f1-14a9-4434-916c-a12c2e230947": {
        "objectId": "43ec72f1-14a9-4434-916c-a12c2e230947",
        "objectType": "PROCESS_INTERFACE_DESCRIPTION",
        "implementation": "PROCESSING_ELEMENT",
        "name": "Not",
        "inports": {
            "a3714110-1fba-4b01-a1b7-8a8ed7310384": {
                "name": "In",
                "objectId": "a3714110-1fba-4b01-a1b7-8a8ed7310384",
                "objectType": "INPORT",
                "requiredTypes": [
                    "BOOLEAN"
                ],
                "desiredUnits": [],
                "generatesResponse": "PASSTHROUGH",
                "index": 0
            }
        },
        "outports": {
            "7ff3e382-e058-44f3-9293-d1a8d805bfd8": {
                "name": "Out",
                "objectId": "7ff3e382-e058-44f3-9293-d1a8d805bfd8",
                "objectType": "OUTPORT",
                "types": [
                    "BOOLEAN"
                ],
                "index": 0
            }
        },
        "portTemplates": {}
    },
    "e3cc50a9-795c-4a47-8643-6d0aee39b49c": {
        "objectId": "e3cc50a9-795c-4a47-8643-6d0aee39b49c",
        "objectType": "PROCESS_INTERFACE_DESCRIPTION",
        "implementation": "PROCESSING_ELEMENT",
        "name": "Warning",
        "inports": {
            "a3cbcc81-fb06-4bd2-87cd-31c6665de9ce": {
                "name": "Trigger",
                "objectId": "a3cbcc81-fb06-4bd2-87cd-31c6665de9ce",
                "objectType": "INPORT",
                "requiredTypes": [],
                "desiredUnits": [],
                "generatesResponse": "NEVER",
                "index": 0
            }
        },
        "outports": {},
        "portTemplates": {},
        "visualizationHint": "WARNING"
    },
    "41c22bcb-f966-406a-8814-a7b8e187b508": {
        "objectId": "41c22bcb-f966-406a-8814-a7b8e187b508",
        "objectType": "PROCESS_INTERFACE_DESCRIPTION",
        "implementation": "PROCESSING_ELEMENT",
        "name": "Error",
        "inports": {
            "694dacf2-7a7c-4bbb-89eb-6bb3a7461677": {
                "name": "Trigger",
                "objectId": "694dacf2-7a7c-4bbb-89eb-6bb3a7461677",
                "objectType": "INPORT",
                "requiredTypes": [],
                "desiredUnits": [],
                "generatesResponse": "NEVER",
                "index": 0
            }
        },
        "outports": {},
        "portTemplates": {},
        "visualizationHint": "ERROR"
    },
    "26ec17f3-cce9-4854-a139-49d65ed6dc0e": {
        "objectId": "26ec17f3-cce9-4854-a139-49d65ed6dc0e",
        "objectType": "PROCESS_INTERFACE_DESCRIPTION",
        "implementation": "PROCESSING_ELEMENT",
        "name": "Divide and Round Up",
        "inports": {
            "6634faf4-9d9f-4ec8-be06-fa1e65ce05ff": {
                "name": "Numerator",
                "objectId": "6634faf4-9d9f-4ec8-be06-fa1e65ce05ff",
                "objectType": "INPORT",
                "requiredTypes": [
                    "NUMBER"
                ],
                "desiredUnits": [],
                "generatesResponse": "PASSTHROUGH",
                "index": 0
            },
            "81332654-3a4a-4b79-b7ee-a86e7b568b1a": {
                "name": "Divisor",
                "objectId": "81332654-3a4a-4b79-b7ee-a86e7b568b1a",
                "objectType": "INPORT",
                "requiredTypes": [
                    "NUMBER"
                ],
                "desiredUnits": [],
                "generatesResponse": "PASSTHROUGH",
                "index": 1
            }
        },
        "outports": {
            "3c175cbd-2dd4-4ef6-8e31-bddb90e1f61c": {
                "name": "Out",
                "objectId": "3c175cbd-2dd4-4ef6-8e31-bddb90e1f61c",
                "objectType": "OUTPORT",
                "types": [
                    "NUMBER"
                ],
                "index": 0
            }
        },
        "portTemplates": {
            "26e6f598-b27e-4f10-80e2-43e5e6964bb5": {
                "name": "Divisor Multiplier",
                "objectId": "26e6f598-b27e-4f10-80e2-43e5e6964bb5",
                "objectType": "PROCESS_PORT_TEMPLATE",
                "inportTemplates": {
                    "7dae1a52-193e-40cd-b1d1-686bcace8bbe": {
                        "name": "Divisor Multiplier",
                        "objectId": "7dae1a52-193e-40cd-b1d1-686bcace8bbe",
                        "objectType": "INPORT",
                        "requiredTypes": [
                            "NUMBER"
                        ],
                        "desiredUnits": [],
                        "generatesResponse": "PASSTHROUGH",
                        "index": 0
                    }
                },
                "outportTemplates": {}
            }
        }
    },
    "bdc9e038-2d18-40a4-ae71-4a707e1f08c7": {
        "objectId": "bdc9e038-2d18-40a4-ae71-4a707e1f08c7",
        "objectType": "PROCESS_INTERFACE_DESCRIPTION",
        "implementation": "PROCESSING_ELEMENT",
        "name": "Remove Unit",
        "inports": {
            "30f50f34-e265-4add-98d8-0142be665d9d": {
                "name": "In",
                "objectId": "30f50f34-e265-4add-98d8-0142be665d9d",
                "objectType": "INPORT",
                "requiredTypes": [],
                "desiredUnits": [],
                "generatesResponse": "PASSTHROUGH",
                "index": 0
            }
        },
        "outports": {
            "68b7b805-1e9f-438c-be73-29b9a1dc88fb": {
                "name": "Out",
                "objectId": "68b7b805-1e9f-438c-be73-29b9a1dc88fb",
                "objectType": "OUTPORT",
                "types": [],
                "index": 0
            }
        },
        "portTemplates": {}
    },
    "a6b4b5d8-5175-4ae5-8e14-af439a4d6fc9": {
        "objectId": "a6b4b5d8-5175-4ae5-8e14-af439a4d6fc9",
        "objectType": "PROCESS_INTERFACE_DESCRIPTION",
        "implementation": "PROCESSING_ELEMENT",
        "name": "Remove Response",
        "inports": {
            "5408de79-a9c5-4ccb-b322-ce3d6b6a1a86": {
                "name": "In",
                "objectId": "5408de79-a9c5-4ccb-b322-ce3d6b6a1a86",
                "objectType": "INPORT",
                "requiredTypes": [],
                "desiredUnits": [],
                "generatesResponse": "NEVER",
                "index": 0
            }
        },
        "outports": {
            "c071deeb-ef08-44b3-8e00-bb0bdaab3a20": {
                "name": "Out",
                "objectId": "c071deeb-ef08-44b3-8e00-bb0bdaab3a20",
                "objectType": "OUTPORT",
                "types": [],
                "index": 0
            }
        },
        "portTemplates": {}
    },
    "bda55420-1bd1-4e4e-bceb-da993d3040cc": {
        "objectId": "bda55420-1bd1-4e4e-bceb-da993d3040cc",
        "objectType": "PROCESS_INTERFACE_DESCRIPTION",
        "implementation": "PROCESSING_ELEMENT",
        "name": "Remove Aspect",
        "inports": {
            "dba4d0fa-2717-4c67-8357-0a1351ad278d": {
                "name": "In",
                "objectId": "dba4d0fa-2717-4c67-8357-0a1351ad278d",
                "objectType": "INPORT",
                "requiredTypes": [],
                "desiredUnits": [],
                "generatesResponse": "PASSTHROUGH",
                "index": 0
            }
        },
        "outports": {
            "e3ee82f7-dfbc-42ca-bc76-3b8d1537c3b2": {
                "name": "Out",
                "objectId": "e3ee82f7-dfbc-42ca-bc76-3b8d1537c3b2",
                "objectType": "OUTPORT",
                "types": [],
                "index": 0
            }
        },
        "portTemplates": {}
    },
    "ebf77855-9624-46a6-a1d9-7eb756343c66": {
        "objectId": "ebf77855-9624-46a6-a1d9-7eb756343c66",
        "objectType": "PROCESS_INTERFACE_DESCRIPTION",
        "implementation": "PROCESSING_ELEMENT",
        "name": "Extract Breakdown",
        "inports": {
            "ce00c1e2-0677-4c3e-8e58-e7bce8c1b088": {
                "name": "Load",
                "objectId": "ce00c1e2-0677-4c3e-8e58-e7bce8c1b088",
                "objectType": "INPORT",
                "requiredTypes": [
                    "NUMBER"
                ],
                "desiredUnits": [],
                "generatesResponse": "PASSTHROUGH",
                "index": 0
            },
            "9fd695a2-6830-11e9-a923-1681be663d3e": {
                "objectId": "9fd695a2-6830-11e9-a923-1681be663d3e",
                "objectType": "INPORT",
                "name": "Aspect Name",
                "requiredTypes": [
                    "STRING"
                ],
                "desiredUnits": [],
                "generatesResponse": "NEVER",
                "index": 1
            }
        },
        "outports": {
            "71646d47-3371-4579-bd12-50dfb262b425": {
                "name": "Aspect",
                "objectId": "71646d47-3371-4579-bd12-50dfb262b425",
                "objectType": "OUTPORT",
                "types": [
                    "BREAKDOWN"
                ],
                "index": 0
            }
        },
        "portTemplates": {}
    },
    "afe75ba2-2530-4fa7-82e6-a2e0bdc3f5d6": {
        "objectId": "afe75ba2-2530-4fa7-82e6-a2e0bdc3f5d6",
        "objectType": "PROCESS_INTERFACE_DESCRIPTION",
        "implementation": "PROCESSING_ELEMENT",
        "name": "Max",
        "inports": {
            "cfad3400-064a-47eb-a18b-2e325161e43b": {
                "name": "In-A",
                "objectId": "cfad3400-064a-47eb-a18b-2e325161e43b",
                "objectType": "INPORT",
                "requiredTypes": [
                    "NUMBER"
                ],
                "desiredUnits": [],
                "generatesResponse": "PASSTHROUGH",
                "index": 0
            },
            "62fecc4a-042c-4043-b8f5-82e2c7dd06df": {
                "name": "In-B",
                "objectId": "62fecc4a-042c-4043-b8f5-82e2c7dd06df",
                "objectType": "INPORT",
                "requiredTypes": [
                    "NUMBER"
                ],
                "desiredUnits": [],
                "generatesResponse": "PASSTHROUGH",
                "index": 1
            }
        },
        "outports": {
            "66622dbf-0d69-4a02-8954-0cbbf418eb72": {
                "name": "Out",
                "objectId": "66622dbf-0d69-4a02-8954-0cbbf418eb72",
                "objectType": "OUTPORT",
                "types": [
                    "NUMBER"
                ],
                "index": 0
            }
        },
        "portTemplates": {
            "71249ab1-e530-48b3-9073-69f0d5256312": {
                "name": "In-X",
                "objectId": "71249ab1-e530-48b3-9073-69f0d5256312",
                "objectType": "PROCESS_PORT_TEMPLATE",
                "description": "Add an additional inport for the comparison.",
                "inportTemplates": {
                    "49400269-2a72-4e30-9455-3ef3d8fd8072": {
                        "name": "In-X",
                        "objectId": "49400269-2a72-4e30-9455-3ef3d8fd8072",
                        "objectType": "INPORT",
                        "requiredTypes": [
                            "NUMBER"
                        ],
                        "desiredUnits": [],
                        "generatesResponse": "PASSTHROUGH",
                        "index": 0
                    }
                },
                "outportTemplates": {}
            }
        }
    },
    "f7bc3e3e-7719-4662-93ba-fbc7f79481e1": {
        "objectId": "f7bc3e3e-7719-4662-93ba-fbc7f79481e1",
        "objectType": "PROCESS_INTERFACE_DESCRIPTION",
        "implementation": "PROCESSING_ELEMENT",
        "name": "Max (Weighted)",
        "inports": {
            "98af41f8-7cd6-4f98-8e2c-97acdce1db82": {
                "name": "In-A",
                "objectId": "98af41f8-7cd6-4f98-8e2c-97acdce1db82",
                "objectType": "INPORT",
                "requiredTypes": [
                    "NUMBER"
                ],
                "desiredUnits": [],
                "generatesResponse": "PASSTHROUGH",
                "index": 0
            },
            "f87575d3-303f-40df-9d01-02fad14ec285": {
                "name": "In-B",
                "objectId": "f87575d3-303f-40df-9d01-02fad14ec285",
                "objectType": "INPORT",
                "requiredTypes": [
                    "NUMBER"
                ],
                "desiredUnits": [],
                "generatesResponse": "PASSTHROUGH",
                "index": 1
            }
        },
        "outports": {
            "380b54db-2e52-4292-8c67-c372113b9100": {
                "name": "Out",
                "objectId": "380b54db-2e52-4292-8c67-c372113b9100",
                "objectType": "OUTPORT",
                "types": [
                    "NUMBER"
                ],
                "index": 0
            }
        },
        "portTemplates": {
            "dc352282-694b-41c9-a066-57e1c9d0a77d": {
                "name": "In-X",
                "objectId": "dc352282-694b-41c9-a066-57e1c9d0a77d",
                "objectType": "PROCESS_PORT_TEMPLATE",
                "description": "Add an additional inport for the comparison.",
                "inportTemplates": {
                    "e590105a-1e30-403e-be01-9f64b16de156": {
                        "name": "In-X",
                        "objectId": "e590105a-1e30-403e-be01-9f64b16de156",
                        "objectType": "INPORT",
                        "requiredTypes": [
                            "NUMBER"
                        ],
                        "desiredUnits": [],
                        "generatesResponse": "PASSTHROUGH",
                        "index": 0
                    }
                },
                "outportTemplates": {}
            }
        }
    },
    "4642ea8a-1c77-4b08-96a8-73eb8d204ae2": {
        "objectId": "4642ea8a-1c77-4b08-96a8-73eb8d204ae2",
        "objectType": "PROCESS_INTERFACE_DESCRIPTION",
        "implementation": "PROCESSING_ELEMENT",
        "name": "Min",
        "inports": {
            "3e2b3e71-b36e-4a28-9264-4d1d833f3a71": {
                "name": "In-A",
                "objectId": "3e2b3e71-b36e-4a28-9264-4d1d833f3a71",
                "objectType": "INPORT",
                "requiredTypes": [
                    "NUMBER"
                ],
                "desiredUnits": [],
                "generatesResponse": "PASSTHROUGH",
                "index": 0
            },
            "66717e9c-44ef-47f2-8a53-7d7494af501b": {
                "name": "In-B",
                "objectId": "66717e9c-44ef-47f2-8a53-7d7494af501b",
                "objectType": "INPORT",
                "requiredTypes": [
                    "NUMBER"
                ],
                "desiredUnits": [],
                "generatesResponse": "PASSTHROUGH",
                "index": 1
            }
        },
        "outports": {
            "bc2f6b1f-3a3f-43c7-8dc1-4755e562362f": {
                "name": "Out",
                "objectId": "bc2f6b1f-3a3f-43c7-8dc1-4755e562362f",
                "objectType": "OUTPORT",
                "types": [
                    "NUMBER"
                ],
                "index": 0
            }
        },
        "portTemplates": {
            "27149017-e3fc-42f1-93c5-a8766dbe344d": {
                "name": "In-X",
                "objectId": "27149017-e3fc-42f1-93c5-a8766dbe344d",
                "objectType": "PROCESS_PORT_TEMPLATE",
                "description": "Add an additional inport for the comparison.",
                "inportTemplates": {
                    "56d36a1f-b98d-4336-a1a0-1c2c6fd9fc61": {
                        "name": "In-X",
                        "objectId": "56d36a1f-b98d-4336-a1a0-1c2c6fd9fc61",
                        "objectType": "INPORT",
                        "requiredTypes": [
                            "NUMBER"
                        ],
                        "desiredUnits": [],
                        "generatesResponse": "PASSTHROUGH",
                        "index": 0
                    }
                },
                "outportTemplates": {}
            }
        }
    },
    "bf195969-ca1a-4924-91ce-57fbe6da371f": {
        "objectId": "bf195969-ca1a-4924-91ce-57fbe6da371f",
        "objectType": "PROCESS_INTERFACE_DESCRIPTION",
        "implementation": "PROCESSING_ELEMENT",
        "name": "Set Unit",
        "inports": {
            "df042fe4-b146-4725-ae1c-d4f6c5a4dc6f": {
                "name": "Load",
                "objectId": "df042fe4-b146-4725-ae1c-d4f6c5a4dc6f",
                "objectType": "INPORT",
                "requiredTypes": [],
                "desiredUnits": [],
                "generatesResponse": "PASSTHROUGH",
                "index": 0
            },
            "19333fd7-278b-4e28-9d5d-c849f489fa58": {
                "name": "Unit",
                "objectId": "19333fd7-278b-4e28-9d5d-c849f489fa58",
                "objectType": "INPORT",
                "requiredTypes": [
                    "STRING"
                ],
                "desiredUnits": [],
                "generatesResponse": "NEVER",
                "index": 1
            }
        },
        "outports": {
            "0cf3bb07-bd23-4aab-b65d-6912105cb463": {
                "name": "Out",
                "objectId": "0cf3bb07-bd23-4aab-b65d-6912105cb463",
                "objectType": "OUTPORT",
                "types": [
                    "NUMBER"
                ],
                "index": 0
            }
        },
        "portTemplates": {}
    },
    "752583fd-bc36-4604-9d5f-a276e9974c46": {
        "objectId": "752583fd-bc36-4604-9d5f-a276e9974c46",
        "objectType": "PROCESS_INTERFACE_DESCRIPTION",
        "implementation": "PROCESSING_ELEMENT",
        "name": "Test Same Unit",
        "inports": {
            "92f778c4-4004-4c27-999a-b5964eee5911": {
                "name": "In-A",
                "objectId": "92f778c4-4004-4c27-999a-b5964eee5911",
                "objectType": "INPORT",
                "requiredTypes": [],
                "desiredUnits": [],
                "generatesResponse": "NEVER",
                "index": 0
            },
            "58e3d41f-49f5-413c-a0c6-4a1a960d6f81": {
                "name": "In-B",
                "objectId": "58e3d41f-49f5-413c-a0c6-4a1a960d6f81",
                "objectType": "INPORT",
                "requiredTypes": [],
                "desiredUnits": [],
                "generatesResponse": "NEVER",
                "index": 1
            }
        },
        "outports": {
            "46271475-2356-45b9-b32a-317130f733e9": {
                "name": "Out",
                "objectId": "46271475-2356-45b9-b32a-317130f733e9",
                "objectType": "OUTPORT",
                "types": [
                    "BOOLEAN"
                ],
                "index": 0
            }
        },
        "portTemplates": {
            "a1c3068b-d519-4b50-bffb-11e77c227596": {
                "name": "In-X",
                "objectId": "a1c3068b-d519-4b50-bffb-11e77c227596",
                "objectType": "PROCESS_PORT_TEMPLATE",
                "description": "Add an additional inport for the comparison.",
                "inportTemplates": {
                    "2da68923-81de-49f2-9e75-5936420135ab": {
                        "name": "In-X",
                        "objectId": "2da68923-81de-49f2-9e75-5936420135ab",
                        "objectType": "INPORT",
                        "requiredTypes": [],
                        "desiredUnits": [],
                        "generatesResponse": "NEVER",
                        "index": 0
                    }
                },
                "outportTemplates": {}
            }
        }
    },
    "b06160a3-1573-4568-93f1-6e4473efcd9b": {
        "objectId": "b06160a3-1573-4568-93f1-6e4473efcd9b",
        "objectType": "PROCESS_INTERFACE_DESCRIPTION",
        "implementation": "PROCESSING_ELEMENT",
        "name": "Test Greater Than",
        "inports": {
            "f7ab1ebe-0869-4738-ac23-6eecb41072ff": {
                "name": "In-A",
                "objectId": "f7ab1ebe-0869-4738-ac23-6eecb41072ff",
                "objectType": "INPORT",
                "requiredTypes": [
                    "NUMBER"
                ],
                "desiredUnits": [],
                "generatesResponse": "NEVER",
                "index": 0
            },
            "d65dde8e-6785-41ed-b2db-7f2a11ad3afa": {
                "name": "In-B",
                "objectId": "d65dde8e-6785-41ed-b2db-7f2a11ad3afa",
                "objectType": "INPORT",
                "requiredTypes": [
                    "NUMBER"
                ],
                "desiredUnits": [],
                "generatesResponse": "NEVER",
                "index": 1
            }
        },
        "outports": {
            "499023d0-81e8-4eaf-b424-0f8230efa876": {
                "name": "A > B",
                "objectId": "499023d0-81e8-4eaf-b424-0f8230efa876",
                "objectType": "OUTPORT",
                "types": [
                    "BOOLEAN"
                ],
                "index": 0
            }
        },
        "portTemplates": {}
    },
    "1bc3082b-a2b2-4192-9016-4ad1177130b5": {
        "objectId": "1bc3082b-a2b2-4192-9016-4ad1177130b5",
        "objectType": "PROCESS_INTERFACE_DESCRIPTION",
        "implementation": "PROCESSING_ELEMENT",
        "name": "Conditional",
        "inports": {
            "ed1ce2ff-0121-49f4-8ec1-f26be3566d83": {
                "name": "Switch",
                "objectId": "ed1ce2ff-0121-49f4-8ec1-f26be3566d83",
                "objectType": "INPORT",
                "requiredTypes": [
                    "BOOLEAN"
                ],
                "desiredUnits": [],
                "generatesResponse": "NEVER",
                "index": 0
            },
            "f44946cd-b292-49f9-9770-af00530d769d": {
                "name": "True",
                "objectId": "f44946cd-b292-49f9-9770-af00530d769d",
                "objectType": "INPORT",
                "requiredTypes": [],
                "desiredUnits": [],
                "generatesResponse": "PASSTHROUGH",
                "index": 1
            },
            "eb40dad4-e3e1-44df-9dc1-f23f060476ee": {
                "name": "False",
                "objectId": "eb40dad4-e3e1-44df-9dc1-f23f060476ee",
                "objectType": "INPORT",
                "requiredTypes": [],
                "desiredUnits": [],
                "generatesResponse": "PASSTHROUGH",
                "index": 2
            }
        },
        "outports": {
            "3ec84792-1305-4fa2-a52a-39310810eb38": {
                "name": "Out",
                "objectId": "3ec84792-1305-4fa2-a52a-39310810eb38",
                "objectType": "OUTPORT",
                "types": [],
                "index": 0
            }
        },
        "portTemplates": {}
    },
    "595fddc9-5684-4a4a-a71e-14ed9885b995": {
        "objectId": "595fddc9-5684-4a4a-a71e-14ed9885b995",
        "objectType": "PROCESS_INTERFACE_DESCRIPTION",
        "implementation": "PROCESSING_ELEMENT",
        "name": "Simulation Date",
        "inports": {},
        "outports": {
            "5b9b238a-fbbb-44c0-b31e-e8e1cff8cb3d": {
                "objectId": "5b9b238a-fbbb-44c0-b31e-e8e1cff8cb3d",
                "objectType": "OUTPORT",
                "name": "Year",
                "types": [
                    "NUMBER"
                ],
                "index": 1
            },
            "ba5ff363-0e26-49fc-9322-5674ee95728d": {
                "objectId": "ba5ff363-0e26-49fc-9322-5674ee95728d",
                "objectType": "OUTPORT",
                "name": "Months",
                "types": [
                    "NUMBER"
                ],
                "index": 2
            }
        },
        "portTemplates": {}
    },
    "498a73a6-a046-43bf-9f59-3847daa52296": {
        "objectId": "498a73a6-a046-43bf-9f59-3847daa52296",
        "objectType": "PROCESS_INTERFACE_DESCRIPTION",
        "implementation": "PROCESSING_ELEMENT",
        "name": "Simulation Interval",
        "inports": {},
        "outports": {
            "c4983ca6-322f-4a8d-9ddf-6bd80aad9ee7": {
                "objectId": "c4983ca6-322f-4a8d-9ddf-6bd80aad9ee7",
                "objectType": "OUTPORT",
                "name": "Days",
                "types": [
                    "NUMBER"
                ],
                "index": 1
            },
            "5e883248-3547-48fa-98df-9e04c513d23a": {
                "objectId": "5e883248-3547-48fa-98df-9e04c513d23a",
                "objectType": "OUTPORT",
                "name": "Hours",
                "types": [
                    "NUMBER"
                ],
                "index": 2
            },
            "c40b53e7-e5f5-47f6-896e-dd90c09277d4": {
                "objectId": "c40b53e7-e5f5-47f6-896e-dd90c09277d4",
                "objectType": "OUTPORT",
                "name": "Minutes",
                "types": [
                    "NUMBER"
                ],
                "index": 3
            },
            "3c254e49-6910-454a-bc28-ba7338716ed0": {
                "objectId": "3c254e49-6910-454a-bc28-ba7338716ed0",
                "objectType": "OUTPORT",
                "name": "Seconds",
                "types": [
                    "NUMBER"
                ],
                "index": 4
            }
        },
        "portTemplates": {}
    },
    "7cd08bf0-da46-4a51-9e3e-61a81921f1a7": {
        "objectId": "7cd08bf0-da46-4a51-9e3e-61a81921f1a7",
        "objectType": "PROCESS_INTERFACE_DESCRIPTION",
        "implementation": "PROCESSING_ELEMENT",
        "name": "Replace Aspect",
        "inports": {
            "7f31dd1c-855e-4bb4-9868-8f083c1beb57": {
                "name": "Load",
                "objectId": "7f31dd1c-855e-4bb4-9868-8f083c1beb57",
                "objectType": "INPORT",
                "requiredTypes": [
                    "NUMBER"
                ],
                "desiredUnits": [],
                "generatesResponse": "PASSTHROUGH",
                "index": 0
            },
            "ec7e2dbb-79ce-4dbe-b6e6-54e111f11d95": {
                "name": "Aspect",
                "objectId": "ec7e2dbb-79ce-4dbe-b6e6-54e111f11d95",
                "objectType": "INPORT",
                "requiredTypes": [
                    "BREAKDOWN",
                    "TAG",
                    "NUMBER"
                ],
                "desiredUnits": [],
                "generatesResponse": "NEVER",
                "index": 1
            }
        },
        "outports": {
            "5a6f3142-70ea-4af2-8a18-eb821ef47cea": {
                "name": "Out",
                "objectId": "5a6f3142-70ea-4af2-8a18-eb821ef47cea",
                "objectType": "OUTPORT",
                "types": [
                    "NUMBER"
                ],
                "index": 0
            }
        },
        "portTemplates": {}
    },
    "23b4f3ff-1e7c-4fb9-b8b0-a98611f58573": {
        "objectId": "23b4f3ff-1e7c-4fb9-b8b0-a98611f58573",
        "objectType": "PROCESS_INTERFACE_DESCRIPTION",
        "implementation": "PROCESSING_ELEMENT",
        "name": "Serial Execution",
        "description": "Forward load downstream. Add up responses.",
        "inports": {
            "7bd20c1f-3b00-40a6-a978-2c3f72e34f47": {
                "objectId": "7bd20c1f-3b00-40a6-a978-2c3f72e34f47",
                "objectType": "INPORT",
                "name": "In",
                "requiredTypes": [],
                "desiredUnits": [],
                "generatesResponse": "PASSTHROUGH",
                "index": 0
            }
        },
        "outports": {
            "2562449c-9f98-443b-803c-a2e2ba998d98": {
                "objectId": "2562449c-9f98-443b-803c-a2e2ba998d98",
                "objectType": "OUTPORT",
                "name": "Out-A",
                "types": [],
                "index": 1
            },
            "6f3fd23e-9566-42bc-877e-e72b2fc5dd3e": {
                "objectId": "6f3fd23e-9566-42bc-877e-e72b2fc5dd3e",
                "objectType": "OUTPORT",
                "name": "Out-B",
                "types": [],
                "index": 2
            }
        },
        "portTemplates": {
            "3f0a3bc0-fe55-4947-a4a8-998205798368": {
                "name": "Serial Output",
                "objectId": "3f0a3bc0-fe55-4947-a4a8-998205798368",
                "objectType": "PROCESS_PORT_TEMPLATE",
                "inportTemplates": {},
                "outportTemplates": {
                    "900afc02-881d-42b2-8632-0d468c4e1137": {
                        "objectId": "900afc02-881d-42b2-8632-0d468c4e1137",
                        "objectType": "OUTPORT",
                        "name": "Serial-Out",
                        "types": [
                            "NUMBER"
                        ],
                        "unit": "tps",
                        "index": 0
                    }
                }
            }
        }
    }
}
